# Site settings
title: "FOR FUTURE"
author: "Ulyanov"
description: 随便写写
keywords: 
biography: 
colophon: 

baseurl: 
url: https://Mikotoo.github.io

twitter_username: 
github_username: Mikotoo
linkedin_username: 
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
