cellRangerPath:
  '/share/home/yzwl_zhangchao/software/cellranger-8.0.0/bin/cellranger'
cellRangerIndex:
  '/share/home/yzwl_zhangchao/Project/soybean_sn/reference/soybean/Wm82v2'
resultDir:
  '/share/home/yzwl_zhangchao/Project/soybean_sn/01_cellRanger/resultDir'
pipelineDir:
  '/share/home/yzwl_zhangchao/Project/soybean_sn/01_cellRanger/resultDir'
genomeBed:
  '/share/home/yzwl_zhangchao/Project/soybean_sn/reference/soybean/Wm82v2_junc.bed'
Samples:
  nodule_large:
    fastq:
      /share/home/yzwl_zhangchao/Project/soybean_sn/01_cellRanger/rawData/nodule_large
    includeIntron:
      True
    expectCell:
      10000
    r2Length:
      91
  nodule_small:
    fastq:
      /share/home/yzwl_zhangchao/Project/soybean_sn/01_cellRanger/rawData/nodule_small
    includeIntron:
      True
    expectCell:
      10000
    r2Length:
      91
  root:
    fastq:
      /share/home/yzwl_zhangchao/Project/soybean_sn/01_cellRanger/rawData/root
    includeIntron:
      True
    expectCell:
      10000
    r2Length:
      91